version: "3"

services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    networks:
      - static_network

  database:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    networks:
      - static_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DATABASE: ${DATABASE_NAME}

  api:
    networks:
      - static_network
    ports:
      - "8080:8080"
    depends_on:
      - database
    env_file: .env


networks:
  static_network:

volumes:
  postgres_data:
